[BDTrainer]
dataset = "stl10"
poison_type = "blend"
data_rate = 1.0
poison_rate = 0.1
num_models = 20

[BDTrainer.WaNet]
cover_rate = 0.1

[BDTrainer.TaCT]
cover_rate = 0.005

[BDTrainer.adaptive_blend]
cover_rate = 0.003

[BDTrainer.adaptive_patch]
cover_rate = 0.006