[Trainer]
dataset = "cifar10" # choices: cifar10, gtsrb, stl10, cifar100, tinyimagenet, imagenet100
train_source = "train" # choices: train, test
clean_budget = 2000 # train_source test will use clean_budget samples
data_rate = 1
poison_rate = 0.1
num_models = 15

[Trainer.WaNet]
cover_rate = 0.1

[Trainer.TaCT]
cover_rate = 0.005

[Trainer.adaptive_blend]
cover_rate = 0.003

[Trainer.adaptive_patch]
cover_rate = 0.006